[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sgpo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "rspolib",
]

[project.optional-dependencies]
dev = ["hypothesis", "pytest"]

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}
